AWSTemplateFormatVersion: '2010-09-09'
Description: RDS Log Dog lambda function
Parameters:
  s3bucket:
    Type: String
    Description: s3 bucket for logs and code
  s3key: 
    Type: String
    Description: lambda code zip
Resources:
  lambdaRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: Allow
            Principal: 
                Service: 
                  - "lambda.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  writeLogsPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: rds-write-logs-policy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: 
              - "s3:Get*"
              - "s3:List*"
              - "s3:PutObject"
            Resource: "*" 
      Roles:
        - Ref: lambdaRole
  readLogsPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: rds-read-logs-policy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: 
              - "rds:Describe*"
              - "rds:DownloadDBLogFilePortion"
            Resource: "*" 
      Roles:
        - Ref: lambdaRole
  writeCloudwatchPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: cw-write-logs-policy
      PolicyDocument: 
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: 
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:*"
      Roles:
        - Ref: lambdaRole
  function:
    Type: "AWS::Lambda::Function"
    Properties: 
      Description: RDS Log Dog function
      Code:
        S3Bucket: '|ref|s3bucket'
        S3Key: '|ref|s3key'
      Environment:
        Variables:
          dstBucket: '|ref|s3bucket'
      Handler: "rds-log-dog.lambda_handler"
      #KmsKeyArn: String
      Role: '|GetAtt|lambdaRole|Arn'
      Runtime: python2.7
      Timeout: 300
      MemorySize: 512
Outputs:
    lambdaFunctionName:
        Value: '|Ref|function'
        Description: name of lambda function
    lambdaFunctionArn:
        Value: 
          Fn::GetAtt:
            - function
            - Arn
        Description: arn of lambda function
